src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Name;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Likes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="Name")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", mappedBy="Name")
     */
    private $Tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Media", inversedBy="Name")
     */
    private $Media;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="Text")
     */
    private $Comments;

    public function __construct()
    {
        $this->Tags = new ArrayCollection();
        $this->Comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(?float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getLikes(): ?int
    {
        return $this->Likes;
    }

    public function setLikes(?int $Likes): self
    {
        $this->Likes = $Likes;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->Tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->Tags->contains($tag)) {
            $this->Tags[] = $tag;
            $tag->addName($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->Tags->contains($tag)) {
            $this->Tags->removeElement($tag);
            $tag->removeName($this);
        }

        return $this;
    }

    public function getMedia(): ?Media
    {
        return $this->Media;
    }

    public function setMedia(?Media $Media): self
    {
        $this->Media = $Media;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->Comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->Comments->contains($comment)) {
            $this->Comments[] = $comment;
            $comment->setText($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->Comments->contains($comment)) {
            $this->Comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getText() === $this) {
                $comment->setText(null);
            }
        }

        return $this;
    }
}

src/Controller/ProductController.php
<?php
namespace App\Controller;
use App\Entity\Product;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use App\Form\ProductFilterType;
use Symfony\Component\Routing\Annotation\Route;
class ProductController extends AbstractController

{
    /**
     * @param Request $request
     * @Route("/product", name="product_list")
     * @return \Symfony\Component\HttpFoundation\Response
     */
	public function listProductAction(Request $request)
	{
        $form = $this->get('form.factory')->create(ProductFilterType::class);

        if ($request->query->has($form->getName())) {
            // manually bind values from the request
            $form->submit($request->query->get($form->getName()));

            // initialize a query builder
            $filterBuilder = $this->getDoctrine()->getManager()
                ->getRepository(Product::class)
                ->createQueryBuilder('e');

            // build the query from the given form object
            $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($form, $filterBuilder);

            // now look at the DQL =)
            var_dump($filterBuilder->getDql());
        }

        $product = $this->getDoctrine()
            ->getRepository(Product::class)
            ->findAll();

        return $this->render('product/list.html.twig', array(
            'form' => $form->createView(),
            'product' => $product
        ));
	}

    /**
     * Search for an product by its id
     * @Route("/product/{id}", name="product_byId")
     */
    public function showProductAction($id)
    {
        $product = $this->getDoctrine()
            ->getRepository(Product::class)
            ->find($id);

        if (!$product) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        }

        return $this->render('product/byId.html.twig', [ 'product' => $product ]);
    }
}

templates/product/byId.html.twig
{# templates/product/byId.html.twig #}
{% extends 'layout.html.twig' %}

{% block headline %} <h2>Product by id</h2> {% endblock %}
{% block content %}
    <a href="{{ path('product_byId', {'id': product.id}) }}">
        <p>article: {{ product.name }}, content: {{ product.price }}</p>
    </a>
{% endblock %}

templates/product/filter.html.twig
{# templates/product/filter.html.twig #}
{% extends 'layout.html.twig' %}

{% block headline %} <h2>List of products</h2> {% endblock %}
{% block content %}
    <form method="get" action=".">
        {{ form_rest(form) }}
        <input type="submit" name="submit-filter" value="filter" />
    </form>
{% endblock %}

templates/product/list.html.twig
{# templates/product/list.html.twig #}
{% extends 'layout.html.twig' %}

{% block headline %} <h2>List of products</h2> {% endblock %}
{% block content %}
    <form method="get" action=".">
        {{ form_rest(form) }}
        <input type="submit" name="submit-filter" value="filter" />
    </form>
    {% for product in product %}
        <a href="{{ path('product_list', {'slug': product.id}) }}">
            <h3>{{ product.name }}</h3>
            <p> price: € {{ product.price }} -- Likes: {{ product.likes }} </p>
            {# {% if product.comments is not null %}
                {% for comment in product.comments %}
                    <li>
                        <a href="#">
                            {{ comment }}
                        </a>
                    </li>
                {% endfor %}
            {% endif %}
            #}
            </a>
    {% endfor %}
{% endblock %}